/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'miguel.reyes' at '5/6/16 3:52 PM' with Gradle 2.13
 *
 * @author miguel.reyes, @date 5/6/16 3:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
